// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DBProductFechasTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dBProductFechas() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1616, 876));
    driver.findElement(By.cssSelector(".body__card:nth-child(2) .body__btn-information")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".react-datepicker__day--013:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--017:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--019:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__month-container:nth-child(5) .react-datepicker__week:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--022:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".react-datepicker__month-container:nth-child(5) .react-datepicker__week:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".react-datepicker__month-container:nth-child(5) .react-datepicker__week:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".react-datepicker__month-container:nth-child(5) > .react-datepicker__month")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--020:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--022:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--020:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--024:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".react-datepicker")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--008:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--016:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--010:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--013:nth-child(3)")).click();
  }
}
